FPS_CONTEXT = {
    "overview": [
        "Siemens GBS CEE FPS delivers tailor-made digital solutions where standard tools are not enough.",
        "Team works across finance, production, technical data, and factory-specific functions with projects spanning sites worldwide.",
        "Core value is unifying diverse data into one model so right information reaches right role from shopfloor to leadership.",
    ],
    "capabilities": [
        "data-driven factories",
        "finance analytics",
        "production solutions",
        "technical data workflows",
        "factory-specific applications",
        "automation",
        "AI/ML/LLM solutions",
        "full lifecycle support",
    ],
    "toolkit": [
        "Power Platform",
        "Power Apps",
        "Power Automate",
        "SharePoint",
        "Microsoft Fabric",
        "Copilot",
        "Mendix",
        "Snowflake",
        "Python",
        "dbt",
        "KNIME",
        "SQL",
        "DevOps",
        "APIs",
        "Code Siemens",
        "AI/ML/LLM",
        "n8n",
        "Altair RapidMiner",
        "Figma",
    ],
    "examples": [
        "OCTOPUS",
        "AVA",
        "FIN analytics",
        "automation",
        "support for Tomáš Raška and related teams",
    ],
}
