title: "MCP server LLM integration"
description: >-
  who knows

text:
  api_key: "SIEMENS_API_KEY"
  base_url: "https://api.siemens.com/llm/v1"
  model: "gpt-oss-120b" # "glm-5"

embedding:
  api_key: "SIEMENS_API_KEY"
  model: "qwen3-embedding-0.6b"

mcp:
  api_key: "SIEMENS_API_KEY"
  base_url: "https://mcp.siemens.com/mcp"

tts:
  api_key: "ELEVENLABS_API_KEY"
  model_id: "eleven_v3" # "eleven_multilingual_v2"
  output_format: "mp3_22050_32" #  # needs to be compatible with video generation
  threads: 5
  # todo: add 1 more czech and 2 english speakers, preferably with different genders
  speakers:
    - name: "Katarína"
      id: "MpbYQvoTmXjHkaxtLiSh"
      language: "cs" # iso language code
      gender: "female" # important for czech language
    - name: "Katarína"
      id: "KXxZd16DiBqt82nbarJx"
      language: "de"
      gender: "female"
    - name: "Katarína"
      id: "cYctNG9CmLHHErrIh5s7"
      language: "en"
      gender: "female"

stt:
  api_key: "SIEMENS_API_KEY"
  base_url: "https://api.siemens.com/llm/v1"
  model: "whisper-large-v3-turbo"
